-- MySQL Script generated by MySQL Workbench
-- 11/04/16 16:42:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema year3database
-- -----------------------------------------------------
-- This is the ERD for our HSE project

-- -----------------------------------------------------
-- Schema year3database
--
-- This is the ERD for our HSE project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `year3database` DEFAULT CHARACTER SET utf8 ;
USE `year3database` ;

-- -----------------------------------------------------
-- Table `year3database`.`Clinics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`Clinics` (
  `ClinicID` INT NOT NULL AUTO_INCREMENT,
  `c_Address1` VARCHAR(225) NOT NULL,
  `c_Address 2` VARCHAR(45) NULL,
  `c_City` VARCHAR(45) NOT NULL,
  `c_County` VARCHAR(45) NOT NULL,
  `c_Tele_Num` INT NOT NULL,
  PRIMARY KEY (`ClinicID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`userRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`userRole` (
  `userRole_id` INT NOT NULL AUTO_INCREMENT,
  `userRole_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userRole_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`Usertbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`Usertbl` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `hashed_pin` VARCHAR(45) NOT NULL,
  `userRole_userRole_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `userRole_userRole_id`),
  INDEX `fk_Usetbl_userRole1_idx` (`userRole_userRole_id` ASC),
  CONSTRAINT `fk_Usetbl_userRole1`
    FOREIGN KEY (`userRole_userRole_id`)
    REFERENCES `year3database`.`userRole` (`userRole_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`Secretary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`Secretary` (
  `Usertbl_user_id` INT NOT NULL,
  `S_FName` VARCHAR(45) NOT NULL,
  `S_LName` VARCHAR(45) NOT NULL,
  `Clinics_ClinicID` INT NOT NULL,
  PRIMARY KEY (`Usertbl_user_id`),
  INDEX `fk_Secretary_Clinics_idx` (`Clinics_ClinicID` ASC),
  INDEX `fk_Secretary_Usertbl1_idx` (`Usertbl_user_id` ASC),
  CONSTRAINT `fk_Secretary_Clinics`
    FOREIGN KEY (`Clinics_ClinicID`)
    REFERENCES `year3database`.`Clinics` (`ClinicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Secretary_Usertbl1`
    FOREIGN KEY (`Usertbl_user_id`)
    REFERENCES `year3database`.`Usertbl` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`Patient` (
  `Usertbl_user_id` INT NOT NULL,
  `p_Fname` VARCHAR(45) NOT NULL,
  `p_Lname` VARCHAR(45) NOT NULL,
  `p_Address1` VARCHAR(45) NOT NULL,
  `p_Address2` VARCHAR(45) NULL,
  `p_city` VARCHAR(45) NOT NULL,
  `p_county` VARCHAR(45) NOT NULL,
  `p_tel_num` INT NOT NULL,
  `p_email` VARCHAR(45) NULL,
  `Usertbl_userRole_userRole_id` INT NOT NULL,
  PRIMARY KEY (`Usertbl_user_id`, `Usertbl_userRole_userRole_id`),
  CONSTRAINT `fk_Patient_Usertbl1`
    FOREIGN KEY (`Usertbl_user_id` , `Usertbl_userRole_userRole_id`)
    REFERENCES `year3database`.`Usertbl` (`user_id` , `userRole_userRole_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`PhysioTherapist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`PhysioTherapist` (
  `Usertbl_user_id` INT NOT NULL,
  `phy_Fname` VARCHAR(45) NOT NULL,
  `phy_Lname` VARCHAR(45) NOT NULL,
  `phy_address1` VARCHAR(45) NOT NULL,
  `phy_address2` VARCHAR(45) NULL,
  `phy_city` VARCHAR(45) NOT NULL,
  `phy_county` VARCHAR(45) NULL,
  `phy_teleNum` VARCHAR(45) NOT NULL,
  `Clinics_ClinicID` INT NOT NULL,
  PRIMARY KEY (`Usertbl_user_id`, `Clinics_ClinicID`),
  INDEX `fk_PhysioTherapist_Usertbl1_idx` (`Usertbl_user_id` ASC),
  INDEX `fk_PhysioTherapist_Clinics1_idx` (`Clinics_ClinicID` ASC),
  CONSTRAINT `fk_PhysioTherapist_Usertbl1`
    FOREIGN KEY (`Usertbl_user_id`)
    REFERENCES `year3database`.`Usertbl` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PhysioTherapist_Clinics1`
    FOREIGN KEY (`Clinics_ClinicID`)
    REFERENCES `year3database`.`Clinics` (`ClinicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`Appointment` (
  `App_id` INT NOT NULL AUTO_INCREMENT,
  `referral_source` VARCHAR(45) NOT NULL,
  `dateOfRef` DATE NOT NULL,
  `dateOfApp` DATE NOT NULL,
  `startOfAppTime` VARCHAR(45) NOT NULL,
  `priority` INT NOT NULL,
  `endOfAppTime` VARCHAR(45) NOT NULL,
  `Attended` TINYINT(1) NOT NULL,
  PRIMARY KEY (`App_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`PatientAppointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`PatientAppointment` (
  `idPatientAppointment` INT NOT NULL,
  `Appointment_App_id` INT NOT NULL,
  PRIMARY KEY (`idPatientAppointment`, `Appointment_App_id`),
  INDEX `fk_PatientAppointment_Appointment1_idx` (`Appointment_App_id` ASC),
  CONSTRAINT `fk_PatientAppointment_Appointment1`
    FOREIGN KEY (`Appointment_App_id`)
    REFERENCES `year3database`.`Appointment` (`App_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`Dischargetbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`Dischargetbl` (
  `discharge_id` INT NOT NULL AUTO_INCREMENT,
  `dis_date` DATETIME NOT NULL,
  `discharge_Method` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`discharge_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `year3database`.`Sessiontbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `year3database`.`Sessiontbl` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `sess_desc` VARCHAR(225) NOT NULL,
  `Dischargetbl_discharge_id` INT NOT NULL,
  PRIMARY KEY (`session_id`, `Dischargetbl_discharge_id`),
  INDEX `fk_Sessiontbl_Dischargetbl1_idx` (`Dischargetbl_discharge_id` ASC),
  CONSTRAINT `fk_Sessiontbl_Dischargetbl1`
    FOREIGN KEY (`Dischargetbl_discharge_id`)
    REFERENCES `year3database`.`Dischargetbl` (`discharge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
